### ISSUE TITLE
Game crash when trying to load up the game

### ISSUE THREAD

**Issue by Rhgx** [kel-cu/WaterPlayer#10]
Recently the country I live in a country (Turkey) that has blocked off access to twitch.tv and for some reason this has caused a issue with the game not loading up and causes a crash. The logs : https://mclo.gs/Mt0ZKzu

**Comment by kel-cu** [comment]
In the near future, when I sit down to update WaterPlayer. I'll disable twitch.tv or make it not to crash

**Comment by Rhgx** [comment]
What can I do until then?

**Comment by kel-cu** [comment]
Well, you won't be able to disable it in the configuration. Better use VPN and after loading you can disable it (if it is allowed in your country, because in Russia they block a bit for these actions on the part of the service).

**Comment by kel-cu** [comment]
Was fixed in [1.1.0-beta.4](https://modrinth.com/mod/waterplayer/version/1.1.0-beta.4)
