### ISSUE TITLE
Не грузится музыка из яндекса

### ISSUE THREAD

**Issue by Mejkiz** [kel-cu/WaterPlayer#11]
Как я понял музыка не грузится из-за того что токен который ты установил, не обновляется у библиотеке. После ребута игры музыка устанавливается

**Comment by kel-cu** [comment]
Из-за ограничений библиотеки, я не могу обновлять список авторизаций. Из-за чего приходится перезапускать игру. В будущем добавлю сообщение в окне для токенов
