### ISSUE TITLE
Сам запрос музыки не работает

### ISSUE THREAD

**Issue by YTHerlic** [kel-cu/WaterPlayer#12]
во вкладке "добавить трек" я вставляю ссылку на плейлист из ютуба, нажимаю загрузить, он пишет "ваш запрос отправлен" в верхнем правом углу, и ничего не происходит. Пытался переустанавливать мод, интернет хороший, но он просто не работает.

**Comment by kel-cu** [comment]
Проблема в библиотеке, которая будет обновлена в версии 2.x

**Comment by PufferBluh** [comment]
> Проблема в библиотеке, которая будет обновлена в версии 2.x

афигенно, думал сообщить об этой херне, но тогда вопрос, зачем публиковать обновы мода, если он итак не работает?

**Comment by kel-cu** [comment]
Во-первых, я не виноват, что кантора числа пи, то есть Google Inc., ограничивает своё API. Во-вторых, я на данный момент занимаюсь разработкой v2.0, которая будет содержать множество переработок. Поэтому я сейчас не публикую никаких альфа версий, т.к. перед выкладыванием нужно тщательно протестировать и убедиться, что оно не вылетит первым рейсом.

Поэтому прошу на меня так не наезжайте, у меня так последнее выгорание от всего этого. **Я в первую очередь - человек**, которому тоже нужен отдых, как физический, так и моральный.

**Comment by PufferBluh** [comment]
> Во-первых, я не виноват, что кантора числа пи, то есть Google Inc., ограничивает своё API. Во-вторых, я на данный момент занимаюсь разработкой v2.0, которая будет содержать множество переработок. Поэтому я сейчас не публикую никаких альфа версий, т.к. перед выкладыванием нужно тщательно протестировать и убедиться, что оно не вылетит первым рейсом.
> 
> Поэтому прошу на меня так не наезжайте, у меня так последнее выгорание от всего этого. **Я в первую очередь - человек**, которому тоже нужен отдых, как физический, так и моральный.

про то что ты человек я знаю, сорян, я просто думал зачем обновлять, я теперь понял, спасибо за инфу
