### ISSUE TITLE
включение музыки опять не работает? 

### ISSUE THREAD

**Issue by PufferBluh** [kel-cu/WaterPlayer#13]
не давно я радовался что музыка опять начала работать, а потом на следующий день бац, и ничего нет, там опять с какими-что штуками проблемы? Или это только у меня?

**Comment by ImGRUI** [comment]
А что именно не работает? Какой-то из сервисов или вообще ничего?

**Comment by PufferBluh** [comment]
Я решил включить музыку через ютуб музыку, и ничего не происходит

**Comment by ImGRUI** [comment]
Скинь логи майнкрафта https://mclo.gs/

**Comment by PufferBluh** [comment]
> Скинь логи майнкрафта https://mclo.gs/

Сорян за пропажу на 4 дня( 
Короче, я сейчас включил музыку и всё заработало, я не знаю как это, но возможно после обновление всё пофиксилось, либо я как всегда стал опять кретином :D, короче, извиняюсь за возможно фейковую ошибку, ну а я пошёл (Кстати, с праздником!)
