### ISSUE TITLE
Поддержка более старых/новых версий майнкрафта

### ISSUE THREAD

**Issue by neontaburetka** [kel-cu/WaterPlayer#17]
после релиза версии 1.0.0, последующие не версии мода не имели поддержки версии майнкрафта 1.20.1 и перешли на 1.20.2 - 1.20.6. Мне хотелось бы узнать будет ли поддержка более старый версий при переходах на новые версии майнкрафта и будут ли переходы модификации на более новые версии майнкрафта или выход новых версий мода будет только на версию майнкрафта  1.20.2 - 1.20.6. я недавно узнал о моде и хочу понять будут ли хотя бы редкие обновления мода на более старые/новые версии майнкрафта хотя бы на версиях на которых он выходил когда-то, как 1.20.1, и тех  на которых он мог бы выходить, как 1.21.x.

**Comment by kel-cu** [comment]
Это зависит от технической возможности, ведь в Майнкрафте изменяется инструментарий, который используется в библиотеки AlinLib и в самом моде. Так-же скажу, что будет переход на 1.21.x будет без совместимости со старыми версиями (Спасибо Mojang, которые в последних снепшотах все нужное поменяли).

На счет портов, я лично не буду портировать на старые версии, таких как 1.20.1, так как для этого нужно будет еще портировать и свою же библиотеку, и это нужно еще это поддерживать, что для меня уже не кайф.

Я все прекрасно понимаю, что не хочется покидать 1.20.1, но со временем придется из-за технической совместимости с кодом игры и мода. Прошу прощения, если вы надеялись на портирования мода на старые версии
