### ISSUE TITLE
Музыка на сервере

### ISSUE THREAD

**Issue by Charizzy** [kel-cu/WaterPlayer#19]
Можно ли как-то сделать, чтобы у меня и у друга на сервере была синхронизирована музыка? Если нет, то будет ли в будущем такая возможность?

**Comment by kel-cu** [comment]
Данной функции нету и не планируется. Так-как мод является Client-side (или понятнее только под клиент, который никак не контактирует с сервером) и данная функция невозможна из-за технических ограничений игры и библиотеки.
