### ISSUE TITLE
Song instantly closes before its played

### ISSUE THREAD

**Issue by spitshaker112** [kel-cu/WaterPlayer#21]
I tried installing this mod and playing a song but it instantly gets removed from the queue, I tried playing song on a playlist and the song would just stay on my screen and the time would stay 0:00.

**Comment by kel-cu** [comment]
YouTube/Spotify?

**Comment by spitshaker112** [comment]
Spotify doesn't show anything when I search and both Youtube's instantly stop playing.

**Comment by kel-cu** [comment]
For Spotify, you need to provide some data (If not specified)
And YouTube may have stopped working in the library, I have now posted versions with updated library (2.0.1, 2.1.0-alpha.3)

**Comment by spitshaker112** [comment]
Thank you very much. It works now
