### ISSUE TITLE
Песни просто так скипаються

### ISSUE THREAD

**Issue by zeSlaim** [kel-cu/WaterPlayer#22]
просто слушаю музыку и смотрю появляеться следуюший трек и он просто пропускаеться

**Comment by kel-cu** [comment]
Хорошо, можете прислать свои логи через mclo.gs и ответить на пару моих вопросов
<hr>

- Какой вы используете сервис?
- Если ютуб, то есть ли у вас зависание в самом ютубе?

**Comment by kel-cu** [comment]
неактивность
