### ISSUE TITLE
songs skipping themselfs 

### ISSUE THREAD

**Issue by JajaGamer** [kel-cu/WaterPlayer#24]
sometimes when i play my playlist , songs skip themselfs , before it was 1 song getting skipped but now it is like 4 of them getting skipped and with no way of playing the song that just got skipped other than relaunching the playlist , it is really annoying

**Comment by kel-cu** [comment]
YouTube?
Russia?

**Comment by ChunkBannedPanda** [comment]
im having a nearly identical issue, my playlist is on US YouTube and it either skips every other song or every song so i end up with a wall of song names; sometimes a song skips mid way through

**Comment by kel-cu** [comment]
Can I ask you to send me the logs?
https://mclo.gs

**Comment by JajaGamer** [comment]
> Can I ask you to send me the logs? https://mclo.gs

what logs ?

**Comment by kel-cu** [comment]
with a playback error, or better yet, game logs

**Comment by JajaGamer** [comment]
> with a playback error, or better yet, game logs

but my game didnt crashed or anything

**Comment by kel-cu** [comment]
Do the same actions that you did before and send the log (preferably closing the game)
![image](https://github.com/user-attachments/assets/5b64c716-ef7a-4cd1-b744-b666d51b4c2d)

**Comment by JajaGamer** [comment]
> Do the same actions that you did before and send the log (preferably closing the game) ![image](https://private-user-images.githubusercontent.com/86980879/356984898-5b64c716-ef7a-4cd1-b744-b666d51b4c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTMwMDcsIm5iZiI6MTcyMzQ1MjcwNywicGF0aCI6Ii84Njk4MDg3OS8zNTY5ODQ4OTgtNWI2NGM3MTYtZWY3YS00Y2QxLWI3NDQtYjY2NmQ1MWI0YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4NTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzQ3YzVjMmU5MTEzMDI5NzA2NmU1YjQ2YzliZjYwZjExNzQ3NDVmZjc4YWRlZmFiN2JkYjdlMmEyZTE0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7N4y2eK-Gs4pHuu5NIRvIJ8bfHEzvH9qkFy0YtmwlCU)
 
 https://mclo.gs/HUux0vK

**Comment by JajaGamer** [comment]
> > Do the same actions that you did before and send the log (preferably closing the game) ![image](https://private-user-images.githubusercontent.com/86980879/356984898-5b64c716-ef7a-4cd1-b744-b666d51b4c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTMwMDcsIm5iZiI6MTcyMzQ1MjcwNywicGF0aCI6Ii84Njk4MDg3OS8zNTY5ODQ4OTgtNWI2NGM3MTYtZWY3YS00Y2QxLWI3NDQtYjY2NmQ1MWI0YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4NTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzQ3YzVjMmU5MTEzMDI5NzA2NmU1YjQ2YzliZjYwZjExNzQ3NDVmZjc4YWRlZmFiN2JkYjdlMmEyZTE0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7N4y2eK-Gs4pHuu5NIRvIJ8bfHEzvH9qkFy0YtmwlCU)
> 
> https://mclo.gs/HUux0vK

so ?

**Comment by ImGRUI** [comment]
Is issue still occurs in alpha 8.4?

**Comment by JajaGamer** [comment]
> Is issue still occurs in alpha 8.4?

Nop , it’s fixed
