### ISSUE TITLE
The playlist editing interface does not work

### ISSUE THREAD

**Issue by Yeetov** [kel-cu/WaterPlayer#3]
Whenever I run the /playlist (name)  command it doesn't do anything. I have the blur mod which quickly blurs the screen after using the command so it doesn't run the command.

**Comment by kel-cu** [comment]
I know, it's just that after rewriting the code to the official mappings it doesn't work. I'm trying to fix it

**Comment by kel-cu** [comment]
Fixed in [commit](https://github.com/simply-kel/WaterPlayer/commit/5a7913081811f18fc57a47749195323e4ef05338)
