### ISSUE TITLE
как это починить?

### ISSUE THREAD

**Issue by girshcatt** [kel-cu/WaterPlayer#35]
![javaw_4LQNX4nmCV](https://github.com/user-attachments/assets/db9d1878-70fc-4e64-afbc-cdfbb6b39504)

**Comment by kel-cu** [comment]
Ссылка плейлиста - это ссылка на плейлист формата WaterPlayer, то есть не Ютуба, не спотифай и т.д.
Вот пример: https://wplayer.ru/MEF9dfI
Конечно надо будет сделать так чтобы это было понятно, но это позже
