### ISSUE TITLE
 can't load spotify playlists

### ISSUE THREAD

**Issue by Gamershy** [kel-cu/WaterPlayer#36]
I'm just unable to load spotify playlists, even copying the ones from the examples on lavasrc won't work. Seems to be an error, though I can make my own playlists just fine.
![image](https://github.com/user-attachments/assets/00c0dfba-f801-4eb5-bac8-2392fce3c85d)
This is the error that appears. Pretty sure something internally is screwed up.

**Comment by ImGRUI** [comment]
Did you type in spotify tokens?

**Comment by ImGRUI** [comment]
If you paste spotify link in WaterPlayer playlist creation, that's not gonna work cause it accepts only names and WaterPlayer playlists. You should firstly create playlist, and then edit URLs for it
