### ISSUE TITLE
Не работает на PojavLauncher

### ISSUE THREAD

**Issue by girshcatt** [kel-cu/WaterPlayer#37]
Интерфейс мода рабочий, все хорошо, но песни не воспроизводится, то есть это не то, что нет звука, а даже полоска воспроизведения не сдвигается

**Comment by ImGRUI** [comment]
WaterPlayer не поддерживает PojavLauncher из-за отсутствия в Pojav необходимой библиотеки для его работы. Для решения проблемы можешь обратиться к разработчику поджава, но это уже обсуждалось ранее в дискорд сервере, безрезультатно.
