### ISSUE TITLE
Проблема Яндекс Музыки

### ISSUE THREAD

**Issue by ghost** [kel-cu/WaterPlayer#5]
На версии 1.1.0-alpha.6 когда я хочу запустить музыку из Яндекс Музыки, она не запускается.
Я не знаю с чем это связано... Токен указал, ссылку вставил, и ничего не получается.
После того как он принял ссылку ничего не следует.

**Comment by kel-cu** [comment]
Возможно вы неправильно указали токен. 
Т.к. у меня он работал :/

**Comment by ghost** [comment]
Я проверил перепроверил токен и с ним всё нормально.
Я вот пытаюсь вставить ссылку, например https://music.yandex.ru/album/17420320/track/89048080, а мод отвечает что мой запрос принят и после этого ничего не следует. Может я неправильную ссылку вставляю?

**Comment by kel-cu** [comment]
Странно, на днях проверю работу Я.Музыки.

**Comment by kel-cu** [comment]
Сейчас попробовал загрузить треки с Я.Музыки, и у меня все работает мой плейлист и тот трек который вы скидывали
![image](https://github.com/simply-kel/WaterPlayer/assets/86980879/a92f9aa3-b885-4042-beed-2e40bd5b4acd)

Но, сейчас посмотрев на issues библиотеки, и там были некоторые проблемы с Я.Музыки. Так что я без понятие какие решения есть для решения вашей проблемы

**Comment by ghost** [comment]
У меня исправилась проблема 😅
Но всё равно спасибо что пытались мне помочь!
