### ISSUE TITLE
Author, Music Time & Music Time Max not getting displayed correctly

### ISSUE THREAD

**Issue by Rhgx** [kel-cu/WaterPlayer#8]
![Picture](https://github.com/simply-kel/WaterPlayer/assets/49099959/0a94039b-3b38-41bf-95c8-2edb0c11966c)

**Comment by kel-cu** [comment]
Can you please tell me the version of the mod?

**Comment by Rhgx** [comment]
1.1.1-beta.1

**Comment by Rhgx** [comment]
Also, I did just update my mod to the latest version (1.1.1-beta.3) but the problem remains.

**Comment by kel-cu** [comment]
If you upgraded from 1.0.x, it is recommended to reset the localization.

**Comment by kel-cu** [comment]
1.1.0* :)

**Comment by Rhgx** [comment]
Thank you, that seems to have fixed it. I'll close the ticket now.
