### ISSUE TITLE
volume is wanky

### ISSUE THREAD

**Issue by libTSC** [kel-cu/WaterPlayer#9]
the volume is hardcoded to 3
trackManager = new TrackScheduler(audioPlayer);
		trackSearch = new TrackSearch(audioPlayerManager, audioPlayer, trackManager);
		audioPlayer.setVolume(WaterPlayer.config.getNumber("CURRENT_MUSIC_VOLUME", 3).intValue());
		setup();
and is no sense of a slider to adjust

**Comment by libTSC** [comment]
i am being stupid, i forgot to investigate code

**Comment by kel-cu** [comment]
heh
